### ISSUE TITLE
Tag npm releases here?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/cwl-ts-auto#11]

**Comment by ZimmerA** [comment]
Done! 😃

**Comment by mr-c** [comment]
Super! I think https://github.com/common-workflow-lab/cwl-ts-auto/releases/tag/v0.1.1 was released to `npm`, yes? So even though it is pre-"1.0" it should not be marked as a "prerelease".

That is used for things like "release candidates" or perhaps even beta releases

**Comment by ZimmerA** [comment]
Ahh I thought it being pre-"1.0" would make it a candidate for prerelease! Will fix that!
