### ISSUE TITLE
Generate and upload documentation

### ISSUE THREAD

**Issue by ZimmerA** [common-workflow-lab/cwl-ts-auto#9]
The interfaces and classes are already documented https://typedoc.org/ can be used for generating the documentation pages.

**Comment by ZimmerA** [comment]
Done! https://common-workflow-lab.github.io/cwl-ts-auto/

**Comment by mr-c** [comment]
They look great, woohoo!

Is there a link in the repo readme?

Do they generate automatically?

**Comment by ZimmerA** [comment]
> They look great, woohoo!
> 
> Is there a link in the repo readme?

Thanks!
Not yet, I will add that on the next release 😄 

> Do they generate automatically?

Currently we have to execute `npm run doc` locally to generate the docs and push them if the codebase changes
